### ISSUE TITLE
Cannot read split of undefined

### ISSUE THREAD

**Issue by Milo123459** [vocksel/roblox-theme-converter#16]
![YX5j8Trx](https://user-images.githubusercontent.com/50248166/129470804-74272a79-823c-4034-90c3-a1e1da00d667.png)

**Comment by vocksel** [comment]
Thanks for the report. Is this the theme you are trying to convert?
https://github.com/material-theme/vsc-community-material-theme

**Comment by Milo123459** [comment]
Yes, that is the theme. The palenight version, I love it dearly.

**Comment by vocksel** [comment]
Circling back to this after moving. Could you please include the results of `rbxtheme --version` and `node --version` please? I am not able to reproduce this on my end with rbxtheme 1.4.0 and node 14.17.2

**Comment by Milo123459** [comment]
Okay:
rbxtheme: 1.4.0
node: 16.7.0

**Comment by Milo123459** [comment]
any updates @vocksel :)
