### ISSUE TITLE
Invalid destructuring of undefined properties on some extensions

### ISSUE THREAD

**Issue by OverHash** [vocksel/roblox-theme-converter#4]
https://github.com/vocksel/rbxtheme/blob/bc65e97c6784746eac7e5985c61297c3c8c97567/src/theme.js#L52

If `pkg.contributes` is undefined, this will error.
![image](https://user-images.githubusercontent.com/46231745/128615815-5640649d-c44e-4f48-ae5a-7751e9fde155.png)

An example extension where this occurs: https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter

**Comment by OverHash** [comment]
A solution such as
```js
const { themes } = pkg.contributes ?? {}
```
would work.

**Comment by vocksel** [comment]
Cool good catch, I'll get a bug fix in for this :)

**Comment by vocksel** [comment]
Could you provide some info on how to repro this? What Node version are you using? And does this error occur when running `rbxtheme`, or is it when you are trying to convert a specific theme?

**Comment by OverHash** [comment]
Node: `v14.17.0`
`rbxtheme list` also causes this error.
`rbxtheme convert "Plastic"` causes this error (though the theme does not matter, as rbxtheme iterates through all extensions anyway).

https://github.com/vocksel/rbxtheme/issues/4#issuecomment-894735337 was a solution that worked for me.

**Comment by vocksel** [comment]
Gotcha, there must be at least one theme you have installed that does not have the `contributes` field then. I'll get a fix in so you and others can use the cli

**Comment by vocksel** [comment]
Please update to the latest version and let me know if this resolves your issue :)

**Comment by OverHash** [comment]
Works perfectly! Thanks!
